In [1]:
import numpy as np
from tensorflow.keras.preprocessing.sequence import TimeseriesGenerator

In [2]:
# Create some dummy data
x = np.arange(1, 11, 1)
y = np.arange(10, 110, 10)

print(x)
print(y)

[ 1  2  3  4  5  6  7  8  9 10]
[ 10  20  30  40  50  60  70  80  90 100]


In [6]:
# Create a time series generator object
ts_gen = TimeseriesGenerator(x, y, length=4)

In [7]:
data, labels = ts_gen[0]
print("Data:\n", data)
print("Labels:\n", labels)

Data:
 [[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]]
Labels:
 [ 50  60  70  80  90 100]


In [9]:
# Generate batches of data
ts_gen = TimeseriesGenerator(x, y, length=4, batch_size=2)

# Make the generator an iterable
ts_gen_iter = iter(ts_gen)

In [10]:
# Loop through batch
next(ts_gen_iter)

(array([[1, 2, 3, 4],
        [2, 3, 4, 5]]), array([50, 60]))

In [11]:
# Change the stride of the time series generator
ts_gen = TimeseriesGenerator(x, y, length=4, batch_size=2, stride=2)

# Make the generator an iterable
ts_gen_iter = iter(ts_gen)

In [15]:
# Loop through each batch
next(ts_gen_iter)

(array([[1, 2, 3, 4],
        [3, 4, 5, 6]]), array([50, 70]))

In [16]:
# We can also reverse the time series for each sample
ts_gen = TimeseriesGenerator(x, y, length=4, batch_size=2, reverse=True)

# Make the generator an iterable
ts_gen_iter = iter(ts_gen)

In [17]:
# Loop through each batch
next(ts_gen_iter)

(array([[4, 3, 2, 1],
        [5, 4, 3, 2]]), array([50, 60]))